[package]
name = "wlc-sys-with_elogind"
version = "0.0.8"
authors = ["Victor Brekenfeld (Drakulix) <github@drakulix.de>"]
build = "build.rs"
description = "Bindgen generated low-level wlc wrapper wiht elogind support"
documentation = "https://drakulix.github.io/wlc/wlc-sys/"
repository = "https://github.com/Honey-Be/wlc.rs/tree/master/wlc-sys"
keywords = ["wayland", "compositor", "bindings"]
categories = ["external-ffi-bindings"]
license = "MIT"
exclude = [".travis.yml", ".rustfmt.toml"]

[lib]
path = "src/lib.rs"

[build-dependencies]
bindgen = "0.22"
cmake = { version = "0.1", optional = true }

[dependencies]
libc = "0.2"

[features]
static = ["cmake"]
